import { Post } from './types'

type MockPost = Omit<Post, 'likeRate' | 'commentRate' | 'shareRate' | 'saveRate' | 'reachMultiplier'>

function hydrate(posts: MockPost[]): Post[] {
  return posts.map(p => ({
    ...p,
    likeRate: p.likes / Math.max(p.views, 1),
    commentRate: p.comments / Math.max(p.views, 1),
    shareRate: p.shares / Math.max(p.views, 1),
    saveRate: p.saves / Math.max(p.views, 1),
    reachMultiplier: p.views / Math.max(p.followerCount, 1),
  }))
}

const RAW_POSTS: MockPost[] = [
  {
    id: 'p001',
    platform: 'tiktok',
    creatorId: 'c001',
    creatorName: 'Maddie Rae',
    creatorHandle: '@maddierae__',
    followerCount: 28400,
    creatorGradient: 'linear-gradient(135deg, #d97706, #ea580c)',
    views: 4_200_000,
    likes: 312_000,
    comments: 8_400,
    shares: 148_000,
    saves: 224_000,
    engagementRate: 16.7,
    saveShareRatio: 0.053,
    velocityViewsPerHour: 318_000,
    growthDelta: 0.94,
    explosionScore: 96,
    audioName: 'Fast Car — Tracy Chapman',
    hashtags: ['country', 'acoustic', 'fastcar', 'viral'],
    niche: ['country', 'acoustic', 'singer-songwriter'],
    geography: 'Nashville, TN',
    artistType: 'independent',
    caption: 'when the song hits different in the car at 2am 🎸 this one got me',
    emoji: '🎸',
    gradient: 'linear-gradient(145deg, #1a0900 0%, #4a1500 40%, #7c2d12 70%, #1c0800 100%)',
    formatCluster: 'car-singalong',
    postUrl: 'https://www.tiktok.com/@maddierae__',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    growthHistory: [0, 180_000, 620_000, 1_400_000, 2_600_000, 3_700_000, 4_200_000],
    aiAnalysis: {
      hookSentence: '"I had a feeling I could be someone..."',
      hookTimingSeconds: 1.1,
      emotionalIntensity: 9.4,
      charismaScore: 8.8,
      whyItWorked: [
        'Iconic song creates instant emotional recognition in under 2 seconds',
        'Intimate close-up framing builds parasocial connection',
        'Zero cuts during the performance — uninterrupted tension builds retention',
        'Natural car lighting (warm, slightly harsh) feels raw and authentic',
        'Caption creates a relatable emotional gap without being performative',
        'Save/share ratio 5× category average — viewers want to return to it',
      ],
      howToRecreate: [
        'Film in car at night or golden hour — no ring light, no studio setup',
        'Start mid-chorus — skip the intro entirely',
        'Lock camera or rest it on dashboard — do not hold it',
        'No jump cuts during the key emotional moment',
        'Choose a song with pre-existing emotional weight in your niche',
        'Caption should feel like a personal thought, never a promotion',
      ],
      viralityFactors: { hook: 96, production: 58, charisma: 91, timing: 88, shareability: 97, authenticity: 95 },
      audienceOverlap: ['country-fans', 'nostalgia-seekers', 'women-25-34', 'midwest-usa'],
      creatorArchetype: 'authentic-everyday',
      relatedFormats: ['bedroom-acoustic', 'emotional-reaction', 'night-drive-cover'],
      editingAnalysis: {
        cutFrequency: '0 cuts (full take)',
        pacing: 'slow-build',
        subtitleStyle: 'none',
        shotTypes: ['extreme close-up', 'face forward', 'static'],
      },
      formatCluster: 'car-singalong',
    },
  },

  {
    id: 'p002',
    platform: 'tiktok',
    creatorId: 'c002',
    creatorName: 'trapbeats.lo',
    creatorHandle: '@trapbeats_lo',
    followerCount: 22_100,
    creatorGradient: 'linear-gradient(135deg, #7c3aed, #4f46e5)',
    views: 3_800_000,
    likes: 241_000,
    comments: 18_200,
    shares: 96_000,
    saves: 187_000,
    engagementRate: 14.3,
    saveShareRatio: 0.049,
    velocityViewsPerHour: 290_000,
    growthDelta: 0.91,
    explosionScore: 94,
    audioName: 'Original Beat — trapbeats.lo',
    hashtags: ['producer', 'cookup', 'trap', 'beatmaking', 'hiphop'],
    niche: ['rap', 'hip-hop', 'producer'],
    geography: 'Atlanta, GA',
    artistType: 'independent',
    caption: 'made this in 12 minutes and i think it might be the one 🔥 full cookup tmrw',
    emoji: '🎛️',
    gradient: 'linear-gradient(145deg, #0f0722 0%, #1e0a3d 40%, #2d1054 70%, #0a0515 100%)',
    formatCluster: 'producer-cookup',
    postUrl: 'https://www.tiktok.com/@trapbeats_lo',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 9).toISOString(),
    growthHistory: [0, 120_000, 480_000, 1_200_000, 2_100_000, 3_100_000, 3_800_000],
    aiAnalysis: {
      hookSentence: '"made this in 12 minutes"',
      hookTimingSeconds: 0.8,
      emotionalIntensity: 7.2,
      charismaScore: 7.6,
      whyItWorked: [
        'Time constraint hook ("12 minutes") creates instant curiosity and stakes',
        'Beat quality visibly exceeds expectation — cognitive dissonance drives shares',
        'Studio environment signals credibility without being intimidating',
        'Comment section becomes a debate (good/bad beat) — algorithm reward',
        'Cliffhanger caption drives follow for "full cookup tmrw"',
        'DAW screen in frame gives producers technical FOMO',
      ],
      howToRecreate: [
        'Lead with a time or constraint ("made this in X") — creates stakes immediately',
        'Show the DAW screen — producers need to see the setup',
        'Let the beat speak for 4–8 bars before cutting',
        'Tease a continuation in the caption to drive follows',
        'Film reaction to your own beat — authentic emotional response signals quality',
        'Post the cookup within 24h to close the loop',
      ],
      viralityFactors: { hook: 92, production: 84, charisma: 74, timing: 90, shareability: 88, authenticity: 86 },
      audienceOverlap: ['producers', 'rap-fans', 'beatmakers', 'men-18-28'],
      creatorArchetype: 'technical-expert',
      relatedFormats: ['sample-flip-reveal', 'beat-reaction', 'studio-session'],
      editingAnalysis: {
        cutFrequency: '1 cut per 3 seconds',
        pacing: 'escalating',
        subtitleStyle: 'bold white center',
        shotTypes: ['screen capture', 'over-shoulder', 'close-up hands'],
      },
      formatCluster: 'producer-cookup',
    },
  },

  {
    id: 'p003',
    platform: 'tiktok',
    creatorId: 'c003',
    creatorName: 'claire voss',
    creatorHandle: '@clairevoss',
    followerCount: 19_300,
    creatorGradient: 'linear-gradient(135deg, #0e7490, #0891b2)',
    views: 3_100_000,
    likes: 278_000,
    comments: 11_400,
    shares: 87_000,
    saves: 196_000,
    engagementRate: 18.5,
    saveShareRatio: 0.063,
    velocityViewsPerHour: 261_000,
    growthDelta: 0.88,
    explosionScore: 93,
    audioName: 'Original — clairevoss',
    hashtags: ['indie', 'singersongwriter', 'bedroom', 'original', 'vulnerability'],
    niche: ['indie', 'pop', 'singer-songwriter'],
    geography: 'Brooklyn, NY',
    artistType: 'independent',
    caption: 'this is the song i was too scared to post. i guess i\'m not anymore',
    emoji: '🌊',
    gradient: 'linear-gradient(145deg, #062b33 0%, #0c4a55 40%, #0e7490 60%, #031a1f 100%)',
    formatCluster: 'vulnerability-reveal',
    postUrl: 'https://www.tiktok.com/@clairevoss',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
    growthHistory: [0, 90_000, 380_000, 980_000, 1_900_000, 2_700_000, 3_100_000],
    aiAnalysis: {
      hookSentence: '"this is the song i was too scared to post"',
      hookTimingSeconds: 0.0,
      emotionalIntensity: 9.7,
      charismaScore: 9.1,
      whyItWorked: [
        'Caption IS the hook — vulnerability stated before a single note plays',
        'Perceived risk of posting creates emotional investment in the viewer',
        'Bedroom aesthetic signals intimacy, not performance',
        'Original song removes comparison — audience evaluates purely emotionally',
        'Highest save ratio in sample — viewers bookmarking for later emotional use',
        '"I guess I\'m not anymore" implies a character arc — viewers want to be part of it',
      ],
      howToRecreate: [
        'Lead with a confession in the caption — make it specific and true',
        'Film in your actual space — no cleanup, no curation',
        'Start playing immediately, no intro talk',
        'Eye contact with camera must feel unguarded, not performed',
        'Original material only — this format dies on covers',
        'Post the "scary" song — audience knows the difference',
      ],
      viralityFactors: { hook: 98, production: 52, charisma: 94, timing: 82, shareability: 91, authenticity: 99 },
      audienceOverlap: ['indie-fans', 'emotional-listeners', 'women-18-32', 'songwriter-community'],
      creatorArchetype: 'vulnerable-artist',
      relatedFormats: ['bedroom-original', 'emotional-confession', 'scary-post'],
      editingAnalysis: {
        cutFrequency: '0 cuts (full take)',
        pacing: 'slow-build',
        subtitleStyle: 'none',
        shotTypes: ['medium close-up', 'eye contact', 'static'],
      },
      formatCluster: 'vulnerability-reveal',
    },
  },

  {
    id: 'p004',
    platform: 'instagram',
    creatorId: 'c004',
    creatorName: 'Miami Mike',
    creatorHandle: '@miamimike',
    followerCount: 8_900,
    creatorGradient: 'linear-gradient(135deg, #dc2626, #b91c1c)',
    views: 2_700_000,
    likes: 198_000,
    comments: 22_100,
    shares: 118_000,
    saves: 89_000,
    engagementRate: 15.8,
    saveShareRatio: 0.044,
    velocityViewsPerHour: 241_000,
    growthDelta: 0.97,
    explosionScore: 96,
    audioName: 'CARNIVAL — ¥$, Kanye West & Ty Dolla $ign',
    hashtags: ['rap', 'miami', 'freestyle', 'carnival', 'viral'],
    niche: ['rap', 'hip-hop', 'freestyle'],
    geography: 'Miami, FL',
    artistType: 'unsigned',
    caption: 'they told me to wait my turn. 🌊🔥',
    emoji: '🌊',
    gradient: 'linear-gradient(145deg, #0a0000 0%, #1f0000 30%, #3b0000 60%, #050000 100%)',
    formatCluster: 'rage-freestyle',
    postUrl: 'https://www.instagram.com/miamimike',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    growthHistory: [0, 210_000, 690_000, 1_400_000, 2_000_000, 2_400_000, 2_700_000],
    aiAnalysis: {
      hookSentence: '"they told me to wait my turn"',
      hookTimingSeconds: 0.0,
      emotionalIntensity: 9.6,
      charismaScore: 9.4,
      whyItWorked: [
        'Caption activates underdog narrative — one of the most universally resonant arcs',
        'Under 9K followers performing at a level that feels impossible — drives sharing',
        'Trending audio at early adoption stage — algorithm boost window still open',
        'Intensity and delivery signals major-label energy from an unsigned creator',
        'Very high comment volume — debate about talent drives secondary shares',
        'Geographic identity (Miami) activates loyal regional fanbase',
      ],
      howToRecreate: [
        'Identify trending audio in its first 48 hours before saturation',
        'Caption should position you as the underdog — never the winner',
        'Deliver 10× harder than the beat demands — overperform the expectation',
        'Keep it under 30 seconds — leave them wanting the full song',
        'Film with energy, even in a small space — performance fills the frame',
        'Geographic identity in hashtags activates local discovery',
      ],
      viralityFactors: { hook: 94, production: 62, charisma: 97, timing: 95, shareability: 94, authenticity: 89 },
      audienceOverlap: ['rap-fans', 'miami', 'men-18-30', 'hip-hop-heads'],
      creatorArchetype: 'breakout-underdog',
      relatedFormats: ['freestyle-over-trending', 'rage-freestyle', 'underdog-moment'],
      editingAnalysis: {
        cutFrequency: '2 cuts per second',
        pacing: 'fast-cut',
        subtitleStyle: 'large bold yellow',
        shotTypes: ['chest-up', 'moving camera', 'low angle'],
      },
      formatCluster: 'rage-freestyle',
    },
  },

  {
    id: 'p005',
    platform: 'tiktok',
    creatorId: 'c005',
    creatorName: 'Tennessee Girl',
    creatorHandle: '@tennesseegirl23',
    followerCount: 12_700,
    creatorGradient: 'linear-gradient(135deg, #92400e, #78350f)',
    views: 2_400_000,
    likes: 187_000,
    comments: 14_200,
    shares: 76_000,
    saves: 143_000,
    engagementRate: 17.5,
    saveShareRatio: 0.060,
    velocityViewsPerHour: 198_000,
    growthDelta: 0.89,
    explosionScore: 91,
    audioName: 'Before He Cheats — Carrie Underwood',
    hashtags: ['country', 'storytime', 'tennessee', 'pov', 'smalltown'],
    niche: ['country', 'storytelling', 'pov'],
    geography: 'Knoxville, TN',
    artistType: 'independent',
    caption: 'pov: you grow up in a small town where everyone knows everything 🤠 part 1',
    emoji: '🌾',
    gradient: 'linear-gradient(145deg, #1a0e00 0%, #3d2000 40%, #5a3010 60%, #120900 100%)',
    formatCluster: 'pov-country-storytime',
    postUrl: 'https://www.tiktok.com/@tennesseegirl23',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    growthHistory: [0, 60_000, 280_000, 760_000, 1_400_000, 2_000_000, 2_400_000],
    aiAnalysis: {
      hookSentence: '"pov: you grow up in a small town where everyone knows everything"',
      hookTimingSeconds: 0.0,
      emotionalIntensity: 8.1,
      charismaScore: 7.9,
      whyItWorked: [
        'POV format activates viewer identity projection — extremely high retention',
        'Small-town nostalgia is one of the most universally resonant country themes',
        '"Part 1" caption drives follow rate — viewer must follow to get resolution',
        'Audio choice (Before He Cheats) signals tone without explaining it',
        'Geographic identity signals authenticity for country niche',
        'Comment section becomes a community — everyone shares their small-town story',
      ],
      howToRecreate: [
        'Open with a POV caption that puts the audience inside a specific scenario',
        'Make the scenario universal but specific — "small town" resonates, "my town" does not',
        'Always end with "part 1" — serialization is free audience retention',
        'Choose audio that emotionally primes before the first word',
        'Leave key details unresolved — curiosity keeps comments coming',
        'Film in-location (outdoors, real environments) for authenticity',
      ],
      viralityFactors: { hook: 91, production: 61, charisma: 79, timing: 84, shareability: 93, authenticity: 92 },
      audienceOverlap: ['country-fans', 'women-18-35', 'midwest-south', 'nostalgia-seekers'],
      creatorArchetype: 'relatable-storyteller',
      relatedFormats: ['pov-country', 'small-town-nostalgia', 'serialized-storytime'],
      editingAnalysis: {
        cutFrequency: '1 cut per 2 seconds',
        pacing: 'steady',
        subtitleStyle: 'white italic script',
        shotTypes: ['medium shot', 'outdoor', 'walk-and-talk'],
      },
      formatCluster: 'pov-country-storytime',
    },
  },

  {
    id: 'p006',
    platform: 'youtube',
    creatorId: 'c006',
    creatorName: 'Ellie Makes Music',
    creatorHandle: '@ellie.makes.music',
    followerCount: 14_200,
    creatorGradient: 'linear-gradient(135deg, #0284c7, #0369a1)',
    views: 1_900_000,
    likes: 167_000,
    comments: 9_800,
    shares: 58_000,
    saves: 134_000,
    engagementRate: 19.4,
    saveShareRatio: 0.071,
    velocityViewsPerHour: 178_000,
    growthDelta: 0.84,
    explosionScore: 91,
    audioName: 'Original — elllie.makes.music',
    hashtags: ['harmonies', 'acapella', 'reveal', 'vocal', 'shorts'],
    niche: ['indie', 'pop', 'vocal', 'harmony'],
    geography: 'Austin, TX',
    artistType: 'independent',
    caption: 'what if I layered it 8 times 🫧',
    emoji: '🎵',
    gradient: 'linear-gradient(145deg, #001a33 0%, #002d52 40%, #004880 60%, #000f1a 100%)',
    formatCluster: 'harmony-stack-reveal',
    postUrl: 'https://www.youtube.com/@ellie.makes.music',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
    growthHistory: [0, 40_000, 200_000, 580_000, 1_100_000, 1_600_000, 1_900_000],
    aiAnalysis: {
      hookSentence: '"what if I layered it 8 times"',
      hookTimingSeconds: 0.0,
      emotionalIntensity: 8.6,
      charismaScore: 8.3,
      whyItWorked: [
        'Escalating format — each layer adds dopamine hit, viewer watches all the way through',
        'Highest save ratio in indie category — viewers keep it as a reference',
        '"What if" framing makes the experiment feel live, not produced',
        'Technical process creates producer/musician FOMO — sharing within niche',
        'The reveal format guarantees a retention cliff at the end — algorithm loves this',
        'Relatable curiosity ("what if") invites duplicates — format spreads virally',
      ],
      howToRecreate: [
        'Start with a simple question: "what if I ___"',
        'Build in layers with a visual indicator (counter, bar, etc.)',
        'The final reveal must pay off more than the viewer expects',
        'Cut between layers quickly — no dead air',
        'Use split screen or stacking layout to show all voices',
        'Short caption — the video explains itself',
      ],
      viralityFactors: { hook: 89, production: 81, charisma: 84, timing: 86, shareability: 90, authenticity: 91 },
      audienceOverlap: ['vocal-enthusiasts', 'music-students', 'indie-fans', 'acapella-fans'],
      creatorArchetype: 'process-revealer',
      relatedFormats: ['demo-to-final', 'layer-reveal', 'studio-experiment'],
      editingAnalysis: {
        cutFrequency: '1 cut per layer transition',
        pacing: 'escalating',
        subtitleStyle: 'counter overlay',
        shotTypes: ['face-cam split', 'studio close-up'],
      },
      formatCluster: 'harmony-stack-reveal',
    },
  },

  {
    id: 'p007',
    platform: 'tiktok',
    creatorId: 'c007',
    creatorName: 'Cole Wyatt',
    creatorHandle: '@cole_wyatt',
    followerCount: 67_400,
    creatorGradient: 'linear-gradient(135deg, #78350f, #92400e)',
    views: 2_100_000,
    likes: 142_000,
    comments: 7_200,
    shares: 63_000,
    saves: 118_000,
    engagementRate: 12.9,
    saveShareRatio: 0.056,
    velocityViewsPerHour: 162_000,
    growthDelta: 0.79,
    explosionScore: 87,
    audioName: 'Original — cole_wyatt',
    hashtags: ['country', 'campfire', 'acoustic', 'original', 'country music'],
    niche: ['country', 'acoustic', 'original'],
    geography: 'Austin, TX',
    artistType: 'independent',
    caption: 'wrote this at 3am after the best night of my life. hope it hits for someone else too 🔥',
    emoji: '🔥',
    gradient: 'linear-gradient(145deg, #150900 0%, #2d1400 40%, #4a1f00 60%, #0d0600 100%)',
    formatCluster: 'campfire-acoustic',
    postUrl: 'https://www.tiktok.com/@cole_wyatt',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    growthHistory: [0, 80_000, 330_000, 800_000, 1_300_000, 1_800_000, 2_100_000],
    aiAnalysis: {
      hookSentence: '"wrote this at 3am after the best night of my life"',
      hookTimingSeconds: 0.0,
      emotionalIntensity: 8.4,
      charismaScore: 8.0,
      whyItWorked: [
        'Time/emotion pairing in caption creates vivid scene before first frame',
        '"Best night of my life" + campfire = instant romanticization',
        'Acoustic original with campfire aesthetic hits peak country fantasy',
        '"Hope it hits for someone else" is a gift frame — selfless sharing prompt',
        'Warm, natural fire lighting is aspirational without being curated',
        'Original material means no copyright issues + no comparison to original artist',
      ],
      howToRecreate: [
        'Film outdoors at night — campfire, porch light, or string lights',
        'Caption should give time + emotional context ("3am", "best night")',
        'Play an original — even if unfinished or rough',
        'Frame the content as a gift to the viewer, not a performance',
        'Keep it under 45 seconds — leave them wanting the full track',
        'Warm tones only — no cold blue lighting for this format',
      ],
      viralityFactors: { hook: 87, production: 63, charisma: 80, timing: 81, shareability: 89, authenticity: 94 },
      audienceOverlap: ['country-fans', 'campfire-aesthetic', 'songwriters', 'men-women-22-40'],
      creatorArchetype: 'campfire-poet',
      relatedFormats: ['car-singalong', 'porch-acoustic', 'night-session'],
      editingAnalysis: {
        cutFrequency: '0 cuts (full take)',
        pacing: 'slow-build',
        subtitleStyle: 'none',
        shotTypes: ['medium shot', 'campfire lit', 'static camera'],
      },
      formatCluster: 'campfire-acoustic',
    },
  },

  {
    id: 'p008',
    platform: 'instagram',
    creatorId: 'c008',
    creatorName: 'K. Jones',
    creatorHandle: '@k.jones_rap',
    followerCount: 45_100,
    creatorGradient: 'linear-gradient(135deg, #1e1b4b, #312e81)',
    views: 1_800_000,
    likes: 124_000,
    comments: 16_700,
    shares: 72_000,
    saves: 81_000,
    engagementRate: 16.3,
    saveShareRatio: 0.045,
    velocityViewsPerHour: 148_000,
    growthDelta: 0.82,
    explosionScore: 88,
    audioName: 'TYPE SHIT — Future, Metro Boomin, Playboi Carti, Travis Scott',
    hashtags: ['rap', 'freestyle', 'bars', 'hiphop', 'unsigned'],
    niche: ['rap', 'hip-hop', 'freestyle'],
    geography: 'Chicago, IL',
    artistType: 'unsigned',
    caption: 'just bars. no cap, no edit, no do-overs 🎤',
    emoji: '🎤',
    gradient: 'linear-gradient(145deg, #050318 0%, #0d0832 40%, #160f4a 60%, #020110 100%)',
    formatCluster: 'no-edit-freestyle',
    postUrl: 'https://www.instagram.com/k.jones_rap',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    growthHistory: [0, 70_000, 290_000, 700_000, 1_200_000, 1_600_000, 1_800_000],
    aiAnalysis: {
      hookSentence: '"no cap, no edit, no do-overs"',
      hookTimingSeconds: 0.0,
      emotionalIntensity: 8.8,
      charismaScore: 9.0,
      whyItWorked: [
        'Transparency declaration ("no edits, no do-overs") removes skepticism — raw feels real',
        'High comment velocity because viewers feel qualified to judge unedited work',
        'Trending audio early adoption (first 72 hours) captured algorithm upswing',
        'Chicago identity activates loyal regional rap community',
        'Delivery quality exceeds production budget expectation — contrast drives shares',
        '"Just bars" framing strips ego — underdog energy activated',
      ],
      howToRecreate: [
        'Declare constraints upfront ("one take", "no edit") — makes the viewer a judge',
        'Use trending audio in its first 72-hour window only',
        'No fancy setup — one camera angle, studio or bedroom, no production',
        'Caption shorter than the video — confidence',
        'Post immediately, do not wait for a "perfect" take',
        'Regional hashtag activates local community amplification',
      ],
      viralityFactors: { hook: 90, production: 58, charisma: 93, timing: 91, shareability: 87, authenticity: 96 },
      audienceOverlap: ['rap-fans', 'chicago', 'men-18-28', 'hip-hop-heads', 'battle-fans'],
      creatorArchetype: 'raw-bars',
      relatedFormats: ['one-take-freestyle', 'challenge-response', 'no-edit-bars'],
      editingAnalysis: {
        cutFrequency: '0 cuts',
        pacing: 'fast-cut',
        subtitleStyle: 'none',
        shotTypes: ['face-cam', 'chest-up', 'static'],
      },
      formatCluster: 'no-edit-freestyle',
    },
  },

  {
    id: 'p009',
    platform: 'tiktok',
    creatorId: 'c009',
    creatorName: 'Soul by Sara',
    creatorHandle: '@soulbysara',
    followerCount: 23_600,
    creatorGradient: 'linear-gradient(135deg, #7e22ce, #6d28d9)',
    views: 2_200_000,
    likes: 201_000,
    comments: 12_400,
    shares: 89_000,
    saves: 162_000,
    engagementRate: 20.7,
    saveShareRatio: 0.074,
    velocityViewsPerHour: 188_000,
    growthDelta: 0.87,
    explosionScore: 92,
    audioName: 'Hallelujah — Leonard Cohen (gospel arrangement)',
    hashtags: ['gospel', 'rnb', 'soul', 'vocal', 'churchgirl'],
    niche: ['r&b', 'soul', 'gospel'],
    geography: 'Houston, TX',
    artistType: 'independent',
    caption: 'the church raised me and the music kept me 🙏🏾 iykyk',
    emoji: '✨',
    gradient: 'linear-gradient(145deg, #1a0033 0%, #2d0052 40%, #4a1080 60%, #0d001a 100%)',
    formatCluster: 'gospel-vocal-cover',
    postUrl: 'https://www.tiktok.com/@soulbysara',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    growthHistory: [0, 55_000, 240_000, 680_000, 1_300_000, 1_900_000, 2_200_000],
    aiAnalysis: {
      hookSentence: '"the church raised me and the music kept me"',
      hookTimingSeconds: 0.0,
      emotionalIntensity: 9.8,
      charismaScore: 9.5,
      whyItWorked: [
        'Identity sentence ("the church raised me") activates recognition from target audience',
        '"IYKYK" creates in-group belonging — Black church community shares aggressively',
        'Gospel arrangement of secular classic creates double recognition hit',
        'Vocal performance quality stuns against low production expectation',
        'Highest save ratio in R&B category — function as an emotional bookmark',
        'First-person spiritual narrative is nearly impossible to manufacture',
      ],
      howToRecreate: [
        'Open with your origin story in one sentence — who made you, musically',
        '"IYKYK" or cultural shorthand activates in-group sharing — use it deliberately',
        'Choose a classic with universal recognition but perform it in your tradition',
        'No over-production — voice and room only for this format',
        'Eye contact must not break during the vocal peak',
        'Film in a space that signals your world (church, home, porch)',
      ],
      viralityFactors: { hook: 97, production: 55, charisma: 97, timing: 88, shareability: 96, authenticity: 99 },
      audienceOverlap: ['gospel-fans', 'rnb-listeners', 'black-church', 'women-22-45', 'houston'],
      creatorArchetype: 'church-trained-vocalist',
      relatedFormats: ['gospel-cover', 'spiritual-reveal', 'cultural-identity'],
      editingAnalysis: {
        cutFrequency: '0 cuts',
        pacing: 'slow-build',
        subtitleStyle: 'none',
        shotTypes: ['medium close-up', 'face-forward', 'static'],
      },
      formatCluster: 'gospel-vocal-cover',
    },
  },

  {
    id: 'p010',
    platform: 'tiktok',
    creatorId: 'c010',
    creatorName: 'Mara Hill',
    creatorHandle: '@marahill',
    followerCount: 31_400,
    creatorGradient: 'linear-gradient(135deg, #065f46, #047857)',
    views: 1_600_000,
    likes: 132_000,
    comments: 8_900,
    shares: 61_000,
    saves: 108_000,
    engagementRate: 19.4,
    saveShareRatio: 0.068,
    velocityViewsPerHour: 142_000,
    growthDelta: 0.76,
    explosionScore: 86,
    audioName: 'Original — marahill (demo to final)',
    hashtags: ['indie', 'demo', 'songwriting', 'behindthescenes', 'original'],
    niche: ['indie', 'pop', 'singer-songwriter'],
    geography: 'Portland, OR',
    artistType: 'independent',
    caption: 'voice note → demo → final. 6 weeks. worth it.',
    emoji: '🌿',
    gradient: 'linear-gradient(145deg, #001a0f 0%, #002d1f 40%, #004a30 60%, #000f08 100%)',
    formatCluster: 'demo-to-final',
    postUrl: 'https://www.tiktok.com/@marahill',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 42).toISOString(),
    growthHistory: [0, 45_000, 190_000, 520_000, 990_000, 1_400_000, 1_600_000],
    aiAnalysis: {
      hookSentence: '"voice note → demo → final"',
      hookTimingSeconds: 0.0,
      emotionalIntensity: 8.2,
      charismaScore: 7.7,
      whyItWorked: [
        'Transformation arc is one of the most reliable retention formats in music content',
        'Short caption summarizes the entire journey — viewer knows what they get',
        '"6 weeks" creates context for the quality improvement — respects the craft',
        'Voice note stage makes the process accessible — "I could do this too"',
        'High save ratio — viewers keep it as a songwriting process reference',
        'Side-by-side or sequential audio comparison creates cognitive delight',
      ],
      howToRecreate: [
        'Save every stage of your song — voice note, voice memo, rough demo, final',
        'Show them in sequence: worst first, best last — the arc IS the hook',
        'Keep caption to 3 stages + time elapsed only — no extra explanation',
        'Audio quality improvement must be clearly audible',
        'This format works best for original material (covers feel less earned)',
        'Add text overlay at each stage so viewers know where they are',
      ],
      viralityFactors: { hook: 88, production: 76, charisma: 76, timing: 82, shareability: 88, authenticity: 93 },
      audienceOverlap: ['indie-fans', 'songwriters', 'music-process-fans', 'women-20-35'],
      creatorArchetype: 'process-storyteller',
      relatedFormats: ['harmony-stack-reveal', 'studio-process', 'six-week-journey'],
      editingAnalysis: {
        cutFrequency: '1 cut per stage',
        pacing: 'escalating',
        subtitleStyle: 'stage label overlay',
        shotTypes: ['phone screen', 'studio close-up', 'face-cam'],
      },
      formatCluster: 'demo-to-final',
    },
  },

  {
    id: 'p011',
    platform: 'tiktok',
    creatorId: 'c011',
    creatorName: 'Jake Country',
    creatorHandle: '@jake_country',
    followerCount: 89_200,
    creatorGradient: 'linear-gradient(135deg, #b45309, #d97706)',
    views: 1_700_000,
    likes: 118_000,
    comments: 9_400,
    shares: 52_000,
    saves: 87_000,
    engagementRate: 13.9,
    saveShareRatio: 0.051,
    velocityViewsPerHour: 128_000,
    growthDelta: 0.68,
    explosionScore: 83,
    audioName: 'Wagon Wheel — Darius Rucker',
    hashtags: ['country', 'live', 'crowdsingalong', 'bar', 'nashville'],
    niche: ['country', 'live', 'crowd-singalong'],
    geography: 'Nashville, TN',
    artistType: 'independent',
    caption: 'when the whole bar knows every word 🍺🎸 this is why we do it',
    emoji: '🍺',
    gradient: 'linear-gradient(145deg, #1a0c00 0%, #3d1f00 40%, #5c3010 60%, #100800 100%)',
    formatCluster: 'crowd-singalong',
    postUrl: 'https://www.tiktok.com/@jake_country',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    growthHistory: [0, 65_000, 270_000, 680_000, 1_100_000, 1_500_000, 1_700_000],
    aiAnalysis: {
      hookSentence: '"when the whole bar knows every word"',
      hookTimingSeconds: 0.0,
      emotionalIntensity: 8.7,
      charismaScore: 8.2,
      whyItWorked: [
        'Social proof at scale — dozens of people singing validates the artist\'s impact',
        'Viewer projects themselves into the crowd — FOMO for the live experience',
        'Classic song choice means no copyright issue + pre-loaded emotional value',
        '"This is why we do it" caption frames it as mission, not content',
        'Live performance proof is the highest-trust content format for musicians',
        'Drives ticket inquiry in comments — measurable commercial outcome',
      ],
      howToRecreate: [
        'Film from the stage looking OUT at the crowd — not at yourself',
        'Make sure crowd is singing before you cut — this is the payoff shot',
        'Use a song with known sing-along chorus in your genre',
        'Caption should be about the moment, not you',
        'Post immediately after the show while emotional state is authentic',
        'Tag the venue — geo-discovery and venue resharing amplifies reach',
      ],
      viralityFactors: { hook: 85, production: 59, charisma: 84, timing: 82, shareability: 91, authenticity: 90 },
      audienceOverlap: ['country-fans', 'live-music-fans', 'nashville', 'bar-culture'],
      creatorArchetype: 'live-performer',
      relatedFormats: ['car-singalong', 'crowd-moment', 'concert-pov'],
      editingAnalysis: {
        cutFrequency: '1 cut per 4 seconds',
        pacing: 'steady',
        subtitleStyle: 'white caption',
        shotTypes: ['wide shot', 'crowd pov', 'artist-perspective'],
      },
      formatCluster: 'crowd-singalong',
    },
  },

  {
    id: 'p012',
    platform: 'youtube',
    creatorId: 'c012',
    creatorName: 'prodbyelle',
    creatorHandle: '@prodbyelle',
    followerCount: 67_800,
    creatorGradient: 'linear-gradient(135deg, #be185d, #9d174d)',
    views: 1_400_000,
    likes: 98_000,
    comments: 11_200,
    shares: 44_000,
    saves: 88_000,
    engagementRate: 17.2,
    saveShareRatio: 0.063,
    velocityViewsPerHour: 118_000,
    growthDelta: 0.72,
    explosionScore: 84,
    audioName: 'Original Sample Flip — prodbyelle',
    hashtags: ['producer', 'sampleflip', 'hiphop', 'beatmaking', 'vinyl'],
    niche: ['rap', 'hip-hop', 'producer', 'sample-based'],
    geography: 'Los Angeles, CA',
    artistType: 'independent',
    caption: 'found this record for $2 at a swap meet and flipped it in an hour 💿',
    emoji: '💿',
    gradient: 'linear-gradient(145deg, #2d0018 0%, #520030 40%, #7a0047 60%, #1a000f 100%)',
    formatCluster: 'sample-flip-reveal',
    postUrl: 'https://www.youtube.com/@prodbyelle',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 52).toISOString(),
    growthHistory: [0, 50_000, 210_000, 560_000, 980_000, 1_250_000, 1_400_000],
    aiAnalysis: {
      hookSentence: '"found this record for $2 at a swap meet"',
      hookTimingSeconds: 0.0,
      emotionalIntensity: 7.8,
      charismaScore: 7.4,
      whyItWorked: [
        '$2 → high-quality beat transformation is one of the great producer archetypes',
        'Swap meet = discovery narrative — viewers experience the hunt vicariously',
        'Time constraint ("in an hour") adds urgency and makes the result impressive',
        'Vinyl aesthetic signals authenticity and knowledge — high producer respect',
        'Before/after audio reveal format guarantees retention to the end',
        'High save ratio — producers bookmark as technique reference',
      ],
      howToRecreate: [
        'Find or pretend to find source material (thrift, swap meet, crate digging)',
        'Price point matters — cheaper = more impressive transformation story',
        'Show the raw sample first (ugly, unprocessed) before the flip',
        'Time constraint creates natural stakes — use it',
        'End with the full beat looping — let them sit in the result',
        'Film in the record store or market if possible',
      ],
      viralityFactors: { hook: 88, production: 82, charisma: 72, timing: 80, shareability: 86, authenticity: 89 },
      audienceOverlap: ['producers', 'hip-hop-heads', 'vinyl-collectors', 'beatmakers'],
      creatorArchetype: 'crate-digger',
      relatedFormats: ['producer-cookup', 'thrift-flip', 'crate-dig'],
      editingAnalysis: {
        cutFrequency: '1 cut per 2 seconds',
        pacing: 'escalating',
        subtitleStyle: 'minimal overlay text',
        shotTypes: ['record close-up', 'turntable', 'DAW screen', 'hands'],
      },
      formatCluster: 'sample-flip-reveal',
    },
  },

  {
    id: 'p013',
    platform: 'twitter',
    creatorId: 'c013',
    creatorName: 'Devonte Hall',
    creatorHandle: '@devontehall',
    followerCount: 41_200,
    creatorGradient: 'linear-gradient(135deg, #4c1d95, #5b21b6)',
    views: 1_300_000,
    likes: 112_000,
    comments: 8_700,
    shares: 51_000,
    saves: 74_000,
    engagementRate: 18.8,
    saveShareRatio: 0.057,
    velocityViewsPerHour: 108_000,
    growthDelta: 0.71,
    explosionScore: 85,
    audioName: 'Original — devontehall',
    hashtags: ['rnb', 'vocals', 'original', 'blackexcellence', 'neosoul'],
    niche: ['r&b', 'soul', 'neo-soul'],
    geography: 'Atlanta, GA',
    artistType: 'independent',
    caption: 'been holding this one 🤍',
    emoji: '🌙',
    gradient: 'linear-gradient(145deg, #1a0033 0%, #2a0055 40%, #3d1080 60%, #0d0020 100%)',
    formatCluster: 'r&b-vocal-reveal',
    postUrl: 'https://x.com/devontehall',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 58).toISOString(),
    growthHistory: [0, 38_000, 160_000, 420_000, 820_000, 1_100_000, 1_300_000],
    aiAnalysis: {
      hookSentence: '"been holding this one"',
      hookTimingSeconds: 0.0,
      emotionalIntensity: 9.1,
      charismaScore: 9.3,
      whyItWorked: [
        '"Been holding this one" implies vulnerability, not promotion — completely different energy',
        'Four-word caption creates the maximum intrigue-to-length ratio',
        'Vocal run execution in first 3 seconds sets immediate quality bar',
        'X/Twitter R&B community amplifies aggressively in first hour',
        'Minimal production around elite vocals — contrast creates impact',
        'Black excellence community shares within niche with high loyalty',
      ],
      howToRecreate: [
        'Caption of 5 words or fewer — anything more kills the mystery',
        '"Been holding" / "been sitting on this" / "finally posting" — delayed reveal energy',
        'First vocal note must be your best — not a warmup, not an intro',
        'No instrumental track necessary — a cappella section is powerful here',
        'Post Tuesday or Wednesday 7–9pm ET for peak R&B Twitter activity',
        'Do not follow up immediately — let it breathe for 24 hours',
      ],
      viralityFactors: { hook: 91, production: 52, charisma: 95, timing: 88, shareability: 89, authenticity: 96 },
      audienceOverlap: ['rnb-listeners', 'neo-soul-fans', 'atlanta', 'black-music-community'],
      creatorArchetype: 'understated-virtuoso',
      relatedFormats: ['vocal-showcase', 'quiet-flex', 'gospel-vocal-cover'],
      editingAnalysis: {
        cutFrequency: '0 cuts',
        pacing: 'slow-build',
        subtitleStyle: 'none',
        shotTypes: ['face close-up', 'low light', 'static'],
      },
      formatCluster: 'r&b-vocal-reveal',
    },
  },

  {
    id: 'p014',
    platform: 'tiktok',
    creatorId: 'c014',
    creatorName: 'Whitney Sings',
    creatorHandle: '@whitneysings',
    followerCount: 34_100,
    creatorGradient: 'linear-gradient(135deg, #9a3412, #c2410c)',
    views: 1_200_000,
    likes: 92_000,
    comments: 6_800,
    shares: 44_000,
    saves: 77_000,
    engagementRate: 18.3,
    saveShareRatio: 0.064,
    velocityViewsPerHour: 98_000,
    growthDelta: 0.69,
    explosionScore: 82,
    audioName: 'Original — whitneysings',
    hashtags: ['country', 'beforeandafter', 'vocal', 'transformation', 'indie'],
    niche: ['country', 'indie', 'singer-songwriter'],
    geography: 'Nashville, TN',
    artistType: 'independent',
    caption: 'me at 16 vs me now. the voice grows with you 🌱',
    emoji: '🌱',
    gradient: 'linear-gradient(145deg, #1a0a00 0%, #3d1800 40%, #5c2800 60%, #0d0500 100%)',
    formatCluster: 'before-after-vocal',
    postUrl: 'https://www.tiktok.com/@whitneysings',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 66).toISOString(),
    growthHistory: [0, 35_000, 150_000, 390_000, 750_000, 1_050_000, 1_200_000],
    aiAnalysis: {
      hookSentence: '"me at 16 vs me now"',
      hookTimingSeconds: 0.0,
      emotionalIntensity: 8.3,
      charismaScore: 7.8,
      whyItWorked: [
        'Before/after format is the most dependable transformation arc in creator content',
        'Age specificity ("16") makes it relatable — everyone remembers their early voice',
        '"The voice grows with you" is a universal truth that invites personal reflection',
        'Artists share to mark their own journey — drives creator-to-creator amplification',
        'Encouragement content performs better than flex content in this niche',
        'Comment section fills with singers sharing their own journey',
      ],
      howToRecreate: [
        'Find real old footage — the quality difference itself is part of the story',
        'Specific age ("at 16") outperforms general timeframe ("younger me")',
        'End with wisdom, not triumph — "the voice grows with you" over "look how far I came"',
        'Keep both clips under 20 seconds each — transformation arc needs to complete fast',
        'If no old footage, do a "how I used to sing" impression',
        'This format is a gift to younger singers — position it as encouragement',
      ],
      viralityFactors: { hook: 86, production: 58, charisma: 78, timing: 80, shareability: 90, authenticity: 92 },
      audienceOverlap: ['country-fans', 'vocalists', 'aspiring-singers', 'women-18-35'],
      creatorArchetype: 'growth-storyteller',
      relatedFormats: ['demo-to-final', 'vocal-transformation', 'age-progression'],
      editingAnalysis: {
        cutFrequency: '1 cut (the reveal)',
        pacing: 'slow-build',
        subtitleStyle: 'before/after label',
        shotTypes: ['face close-up', 'split screen', 'static'],
      },
      formatCluster: 'before-after-vocal',
    },
  },

  {
    id: 'p015',
    platform: 'instagram',
    creatorId: 'c015',
    creatorName: 'Street Prophet',
    creatorHandle: '@streetprophet',
    followerCount: 34_800,
    creatorGradient: 'linear-gradient(135deg, #1e3a5f, #1e40af)',
    views: 1_100_000,
    likes: 88_000,
    comments: 14_200,
    shares: 46_000,
    saves: 62_000,
    engagementRate: 19.1,
    saveShareRatio: 0.056,
    velocityViewsPerHour: 94_000,
    growthDelta: 0.67,
    explosionScore: 81,
    audioName: 'Lose Yourself — Eminem (slowed)',
    hashtags: ['rap', 'emotional', 'story', 'rnb', 'hiphop'],
    niche: ['rap', 'r&b', 'storytelling'],
    geography: 'Detroit, MI',
    artistType: 'unsigned',
    caption: 'this one\'s for the ones who kept going 🙏',
    emoji: '🙏',
    gradient: 'linear-gradient(145deg, #000d1a 0%, #001533 40%, #00224d 60%, #000610 100%)',
    formatCluster: 'emotional-rap-over-rnb',
    postUrl: 'https://www.instagram.com/streetprophet',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    growthHistory: [0, 30_000, 130_000, 360_000, 680_000, 970_000, 1_100_000],
    aiAnalysis: {
      hookSentence: '"this one\'s for the ones who kept going"',
      hookTimingSeconds: 0.0,
      emotionalIntensity: 9.0,
      charismaScore: 8.6,
      whyItWorked: [
        'Dedication ("this one\'s for") format is the most emotionally generous hook',
        'Vague but universal dedication — everyone has "kept going" through something',
        'Slowed classic creates nostalgia + emotional permission to feel',
        'Detroit identity activates loyal regional community',
        'Combination of rap delivery over emotional R&B bed is cross-genre bridge',
        'Comment section becomes therapy — high community value = high algorithm return',
      ],
      howToRecreate: [
        '"This one\'s for the ones who ___" — fill with a universal experience, not a specific person',
        'Slowed/reverbed classic hit as the audio bed — emotional permission granted',
        'Stay in storytelling mode — do not switch to braggadocio in this format',
        'Film in a raw, undecorated environment — authenticity essential',
        'Let the hook run long — viewers need time to feel before they comment',
        'Post late night — emotional content performs 30% better after 9pm',
      ],
      viralityFactors: { hook: 90, production: 60, charisma: 87, timing: 85, shareability: 88, authenticity: 92 },
      audienceOverlap: ['rap-fans', 'rnb-listeners', 'detroit', 'men-women-20-38'],
      creatorArchetype: 'emotional-narrator',
      relatedFormats: ['dedication-rap', 'slowed-emotional', 'storytelling-bars'],
      editingAnalysis: {
        cutFrequency: '1 cut per 3 seconds',
        pacing: 'steady',
        subtitleStyle: 'lyric overlay italic',
        shotTypes: ['medium shot', 'low light', 'documentary'],
      },
      formatCluster: 'emotional-rap-over-rnb',
    },
  },
]

export const MOCK_POSTS: Post[] = hydrate(RAW_POSTS)
